### ISSUE TITLE
Dependency of diff-fdn-colorless @ 51e45b0 points to a commit that misses .yml files

### ISSUE THREAD

**Issue by svamengualgari** [gdalsanto/rir2fdn#1]
Hi Gloria,

Thanks for sharing your work, I'm excited to give it a try! I cloned the repo with the dependencies, but it seems that the diff-fdn-colorless points to a commit that's misses the .yml files necessary to set up that repo. I'm not sure if I should be doing it differently, but in the meantime I just cloned the diff-fdn-colorless separately and placed them in the 'informed' folder. 

I guess the fix should just be a quick update to the commit pointer in the rir2fdn dependencies.

Best,
Sebastia

**Comment by gdalsanto** [comment]
Hi Sebastia,

Thank you for the comment, I’ve updated the pointer to the diff-fdn-colorless submodule, so it should now include the necessary .yml files.

Please don’t hesitate to reach out if you need any further clarification when you're working with the code:)

Best,
Gloria
